// Generated by CoffeeScript 1.4.0
(function() {
  var Readability, Twitter, app, cfg, express, rdb, tw;

  express = require('express');

  cfg = require('./cfg/config.js');

  Twitter = (require('./lib/twitter.js')).Twitter;

  Readability = (require('./lib/readability.js')).Readability;

  app = express();

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.use(express.session({
    secret: 'blahblahblah'
  }));

  /* Controllers
  */


  tw = new Twitter;

  rdb = new Readability;

  /* Routes
  */


  app.get('/', function(req, res) {
    return res.send("<HTML><BODY><A HREF='/tw'>Twitter: Get Favorites</A><br /><A HREF='/rdb/login'>Readability: Get Access Token</A></BODY></HTML>");
  });

  app.get('/tw', function(req, res) {
    if (req.session.lastFavorite) {
      return tw.getFavoritesFrom(req.session.lastFavorite, function(callback) {
        return res.send(callback);
      });
    } else {
      return tw.getFavoritesFrom(1, function(callback) {
        var lastTweet, tweet, url, _i, _j, _len, _len1, _ref;
        lastTweet = parseInt(callback[0].id) + 50;
        for (_i = 0, _len = callback.length; _i < _len; _i++) {
          tweet = callback[_i];
          _ref = tweet.entities.urls;
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            url = _ref[_j];
            rdb.addBookmark({
              url: url.expanded_url
            });
          }
        }
        req.session.lastFavorite = lastTweet;
        return res.send(callback);
      });
    }
  });

  app.get('/logout', function(req, res) {
    console.log('--- LOGOUT ---');
    console.log(req.session);
    console.log('--- LOGOUT ---');
    req.session.destroy();
    return res.redirect('/');
  });

  /* Readability Auth to retrieve access tokens, etc.
  */


  app.get('/rdb/login', function(req, res) {
    return rdb.login(function(callback) {
      req.session.oauth_token = callback.oauth_token;
      req.session.oauth_token_secret = callback.oauth_token_secret;
      return res.redirect("https://www.readability.com/api/rest/v1/oauth/authorize/?oauth_token=" + callback.oauth_token + "&oauth_token_secret=" + callback.oauth_token_secret);
    });
  });

  app.get('/rdb/callback', function(req, res) {
    console.log('Callback received from Readability');
    console.log(req.query);
    return rdb.handleCallback(req.query.oauth_token, req.session.oauth_token_secret, req.query.oauth_verifier, function(callback) {
      req.session.oauth_access_token = callback.oauth_access_token;
      req.session.oauth_access_token_secret = callback.oauth_access_token_secret;
      return res.send("<HTML><BODY><A HREF='/'>Home</A><BR /><BR /><STRONG>export RDB_ACCESS_TOKEN='" + req.session.oauth_access_token + "'<BR />export RDB_ACCESS_TOKEN_SECRET='" + req.session.oauth_access_token_secret + "</strong><br /><br /><em>Hint: copy/paste this into ~/.profile</BODY></HTML>");
    });
  });

  /* Start the App
  */


  app.listen('3000');

}).call(this);
