// Generated by CoffeeScript 1.4.0

/* Tests for Config /cfg
*/


(function() {
  var cfg, should;

  cfg = require('../cfg/config.js');

  should = require('should');

  describe('Twitter credentials', function() {
    it('Should have a consumer key', function() {
      var tmp;
      tmp = cfg.TW_CONSUMER_KEY;
      return tmp.should.not.eql('');
    });
    it('Should have a consumer secret', function() {
      var tmp;
      tmp = cfg.TW_CONSUMER_SECRET;
      return tmp.should.not.eql('');
    });
    it('Should have an access token', function() {
      var tmp;
      tmp = cfg.TW_ACCESS_TOKEN;
      return tmp.should.not.eql('');
    });
    return it('Should have an access token secret', function() {
      var tmp;
      tmp = cfg.TW_ACCESS_TOKEN_SECRET;
      return tmp.should.not.eql('');
    });
  });

  /* Usage 
  describe('test', function(){
    it('should work with objects', function(){
      var a = { name: 'tobi', age: 2, species: 'ferret' };
      var b = { name: 'jane', age: 8, species: 'ferret' };
      a.should.eql(b);
    })
  
    it('should work with arrays', function(){
      var a = [1,2,{ name: 'tobi' },4,5]
      var b = [1,2,{ name: 'jane' },4,4, 'extra stuff', 'more extra']
      a.should.eql(b);
    })
  
    it('should work with strings', function(){
      'some\nfoo\nbar'.should.equal('some\nbar\nbaz');
    })
  })
  */


}).call(this);
