// Generated by CoffeeScript 1.4.0

/* Tests for Database /lib/db
*/


(function() {
  var Db, cfg, db, should;

  cfg = require('../cfg/config.js');

  should = require('should');

  Db = (require('../lib/db.js')).Db;

  db = new Db(cfg);

  describe('Redis is running', function() {
    var testKey, testValue;
    testKey = 'testKey';
    testValue = 'testValue';
    it('Should be able to set a string', function(done) {
      return db.redis.set(testKey, testValue, done);
    });
    return it('Should be able to get the string we set', function(done) {
      return db.redis.get(testKey, function(err, data) {
        should.not.exist(err);
        data.should.equal(testValue);
        return done();
      });
    });
  });

  describe('Access Tokens', function() {});

}).call(this);
