// Generated by CoffeeScript 1.4.0

/* Tests for Readability /lib/readability
*/


(function() {
  var Readability, Redis, cfg, rdb, redis, should;

  cfg = require('../cfg/config.js');

  should = require('should');

  Readability = (require('../lib/readability.js')).Readability;

  Redis = require('redis');

  redis = Redis.createClient(cfg.REDIS_PORT, cfg.REDIS_HOSTNAME);

  redis.on('error', function(err) {
    return console.log('REDIS Error:' + err);
  });

  rdb = new Readability(cfg, redis);

  describe('Readability connection', function() {
    it('Can retrieve your bookmarks', function(done) {
      return rdb.getBookmarks(function(callback) {
        return done();
      });
    });
    return it('Successfully adds an item to your list', function(done) {
      var item;
      item = {
        url: "http://braddickason.com/my-daily-checklist/"
      };
      return rdb.addBookmark(item, function(callback) {
        return done();
      });
    });
  });

}).call(this);
