// Generated by CoffeeScript 1.4.0

/* Tests for Readability /lib/readability
*/


(function() {
  var Readability, Redis, cfg, rdb, redis, should;

  cfg = require('../cfg/config.js');

  should = require('should');

  Readability = (require('../lib/readability.js')).Readability;

  Redis = require('redis');

  redis = Redis.createClient(cfg.REDIS_PORT, cfg.REDIS_HOSTNAME);

  redis.on('error', function(err) {
    return console.log('REDIS Error:' + err);
  });

  rdb = new Readability(cfg, redis);

  /* Having issues with jenkins configuration
  describe 'Readability connection', ->
    it 'Can retrieve your bookmarks', (done) ->
      rdb.getBookmarks (callback) ->
        done()
      
    it 'Successfully adds an item to your list', (done) ->
      item = {
        url: "http://braddickason.com/my-daily-checklist/"
      }
      
      rdb.addBookmark item, (callback) ->
        done()
  */


}).call(this);
