// Generated by CoffeeScript 1.4.0

/* Tests for Twitter /lib/twitter
*/


(function() {
  var Redis, Twitter, cfg, redis, should, tw;

  cfg = require('../cfg/config.js');

  should = require('should');

  Twitter = (require('../lib/twitter.js')).Twitter;

  Redis = require('redis');

  redis = Redis.createClient(cfg.REDIS_PORT, cfg.REDIS_HOSTNAME);

  redis.on('error', function(err) {
    return console.log('REDIS Error:' + err);
  });

  tw = new Twitter(cfg, redis);

  /* Having issues with Jenkins configuration
  describe 'Twitter connection', ->
    it 'Should retrieve at least one favorite', (done) ->
      tw.getFavorites 10, (callback) ->
        done()
  */


}).call(this);
