// Generated by CoffeeScript 1.4.0

/* Tests for Twitter /lib/twitter
*/


(function() {
  var Twitter, cfg, should, tw;

  cfg = require('../cfg/config.js');

  should = require('should');

  Twitter = (require('../lib/twitter.js')).Twitter;

  tw = new Twitter;

  describe('Twitter connection', function() {
    return it('Should retrieve at least one favorite', function(done) {
      return tw.getFavorites(function(callback) {
        return done();
      });
    });
  });

}).call(this);
