// Generated by CoffeeScript 1.4.0

/* Creates a timer to manage
*/


(function() {
  var Timer;

  exports.Timer = Timer = (function() {

    function Timer(user_name, cfg, db) {
      this.cfg = cfg;
      this.db = db;
      this.id = user_name;
      this.active = false;
      this.interval = {};
    }

    Timer.prototype.startTimer = function(time, callback) {
      var error,
        _this = this;
      error = null;
      if (this.active === true) {
        console.log("Timer is already started");
        return callback("Error: Timer is already started");
      } else {
        this.active = true;
        this.interval = setInterval(function() {
          return console.log(_this.id);
        }, time);
        return callback(error, "Done!");
      }
    };

    Timer.prototype.stopTimer = function(callback) {
      if (this.active === false) {
        console.log("Timer is already stopped");
        return callback("Error: Timer is already stopped");
      } else {
        this.active = false;
        clearInterval(this.interval);
        return callback("Done.");
      }
    };

    return Timer;

  })();

}).call(this);
