// Generated by CoffeeScript 1.4.0

/* Handle integration with Twitter API
*/


(function() {
  var OAuth, Twitter;

  OAuth = (require('oauth')).OAuth;

  exports.Twitter = Twitter = (function() {

    function Twitter(cfg) {
      var oa;
      this.cfg = cfg;
      this.oa = oa = new OAuth('request_url', 'access_url', this.cfg.TW_CONSUMER_KEY, this.cfg.TW_CONSUMER_SECRET, '1.0', 'http://localhost:3000/tw/callback', 'HMAC-SHA1');
    }

    Twitter.prototype.getFavorites = function(count, callback) {
      return this.oa.getProtectedResource('https://api.twitter.com/1.1/favorites/list.json?count=#{count}', 'GET', this.cfg.TW_ACCESS_TOKEN, this.cfg.TW_ACCESS_TOKEN_SECRET, function(error, data, response) {
        if (error) {
          return callback('Error: getting OAuth resource: ' + error);
        } else {
          return callback(JSON.parse(data));
        }
      });
    };

    Twitter.prototype.getFavoritesFrom = function(since, callback) {
      console.log(since);
      return this.oa.getProtectedResource("https://api.twitter.com/1.1/favorites/list.json?since_id=" + since, 'GET', this.cfg.TW_ACCESS_TOKEN, this.cfg.TW_ACCESS_TOKEN_SECRET, function(error, data, response) {
        if (error) {
          callback('Error: getting OAuth resource: ');
          return console.log(error);
        } else {
          return callback(JSON.parse(data));
        }
      });
    };

    return Twitter;

  })();

}).call(this);
