// Generated by CoffeeScript 1.4.0

/* Handle integration with Twitter API
*/


(function() {
  var OAuth, Twitter;

  OAuth = (require('oauth')).OAuth;

  exports.Twitter = Twitter = (function() {

    function Twitter(cfg, redis) {
      var oa;
      this.cfg = cfg;
      this.redis = redis;
      this.oa = oa = new OAuth('https://api.twitter.com/oauth/request_token', 'https://api.twitter.com/oauth/access_token', this.cfg.TW_CONSUMER_KEY, this.cfg.TW_CONSUMER_SECRET, '1.0', "http://" + this.cfg.HOSTNAME + ":" + this.cfg.PORT + "/tw/callback", 'HMAC-SHA1');
    }

    Twitter.prototype.getFavorites = function(user_name, count, callback) {
      var _this = this;
      console.log(user_name);
      return this.redis.hgetall("user:" + user_name + ":Twitter", function(error, reply) {
        console.log(reply);
        if (error) {
          return console.log(error);
        } else {
          return _this.oa.getProtectedResource('https://api.twitter.com/1.1/favorites/list.json?count=#{count}', 'GET', reply.access_token, reply.access_token_secret, function(error, data, response) {
            if (error) {
              return callback('Error: getting OAuth resource: ' + error);
            } else {
              return callback(JSON.parse(data));
            }
          });
        }
      });
    };

    Twitter.prototype.login = function(callback) {
      var _this = this;
      console.log('Getting OAuth Request Token');
      return this.oa.getOAuthRequestToken(function(error, oauth_token, oauth_token_secret, results) {
        if (error) {
          console.log('error :' + JSON.stringify(error));
        }
        return callback({
          oauth_token: oauth_token,
          oauth_token_secret: oauth_token_secret
        });
      });
    };

    Twitter.prototype.handleCallback = function(oauth_token, oauth_token_secret, oauth_verifier, callback) {
      return this.oa.getOAuthAccessToken(oauth_token, oauth_token_secret, oauth_verifier, function(error, oauth_access_token, oauth_access_token_secret, response) {
        if (error) {
          console.log('error :' + JSON.stringify(error));
        }
        if (response === void 0) {
          console.log('error: ' + response);
        }
        return callback({
          oauth_access_token: oauth_access_token,
          oauth_access_token_secret: oauth_access_token_secret,
          "user_name": response.screen_name
        });
      });
    };

    return Twitter;

  })();

}).call(this);
